import json

with open('notebooks/reproduce_anticipation.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 1 (index 1): Environment setup & clone/pull
cell1_source = [
    "import os, sys\n",
    "\n",
    "# Clone repository if not already present, or pull latest\n",
    "if not os.path.exists('data/extracted_features'):\n",
    "    if os.path.exists('anticipation'):\n",
    "        %cd anticipation\n",
    "        !git pull origin main\n",
    "    else:\n",
    "        !git clone https://github.com/fady-nasser/anticipation.git\n",
    "        %cd anticipation\n",
    "else:\n",
    "    !git pull origin main\n",
    "\n",
    "!pip install -q numpy pandas scipy matplotlib seaborn\n",
    "print('Environment and data ready!')\n"
]
nb['cells'][1]['source'] = cell1_source

# Cell 4 (index 4): Self-contained engine
engine_lines = [
    "def zscore(arr):\n",
    "    m = np.nanmean(arr)\n",
    "    s = np.nanstd(arr)\n",
    "    return np.zeros_like(arr) if s < 1e-9 else (arr - m) / s\n",
    "\n",
    "def ols_rss(Y, X):\n",
    "    mask = ~(np.isnan(Y) | np.any(np.isnan(X), axis=1))\n",
    "    if mask.sum() < 15:\n",
    "        return np.nan, 0\n",
    "    Ym, Xm = Y[mask], X[mask]\n",
    "    b, _, _, _ = lstsq(np.c_[np.ones(len(Ym)), Xm], Ym, rcond=None)\n",
    "    r = Ym - np.c_[np.ones(len(Ym)), Xm] @ b\n",
    "    return np.sum(r**2), mask.sum()\n",
    "\n",
    "def make_lags(a, l_list, n):\n",
    "    cols = []\n",
    "    for l in l_list:\n",
    "        c = np.full(n, np.nan)\n",
    "        c[l:] = a[:n-l]\n",
    "        cols.append(c)\n",
    "    return np.column_stack(cols)\n",
    "\n",
    "def run_window_anticipation_counts(npz_path, leaders_dict, followers_dict, \n",
    "                                   outliers=None, window_s=15.0, step_s=7.5, hz=5, lag=2, f_critical=3.14):\n",
    '    """\n',
    "    Computes discrete anticipation counts directly from an extracted velocity features (.npz) file.\n",
    "    No precomputed CSV counts loaded; strictly recalculated via Granger vector autoregression.\n",
    '    """\n',
    "    data = np.load(npz_path)\n",
    "    period = data['period']\n",
    "    ball_x = data['ball_x']\n",
    "    total_pts = len(period)\n",
    "    \n",
    "    window_pts = int(window_s * hz)\n",
    "    step_pts = int(step_s * hz)\n",
    "    n = window_pts\n",
    "    ol = list(range(1, lag + 1))\n",
    "    \n",
    "    all_keys = set(list(leaders_dict.keys()) + list(followers_dict.keys()))\n",
    "    vel_p = {}\n",
    "    for k in all_keys:\n",
    "        vx_k = f'{k}_vx'\n",
    "        vy_k = f'{k}_vy'\n",
    "        if vx_k in data and vy_k in data:\n",
    "            vel_p[k] = (data[vx_k], data[vy_k])\n",
    "            \n",
    "    windows = []\n",
    "    for start in range(0, total_pts - window_pts, step_pts):\n",
    "        end = start + window_pts\n",
    "        if period[start] == period[end - 1]:\n",
    "            bx = ball_x[start:end]\n",
    "            p_win = {k: (vx[start:end], vy[start:end]) for k, (vx, vy) in vel_p.items()}\n",
    "            windows.append((bx, p_win))\n",
    "            \n",
    "    l_names = list(leaders_dict.values())\n",
    "    f_names = list(followers_dict.values())\n",
    "    count_df = pd.DataFrame(0, index=l_names, columns=f_names)\n",
    "    \n",
    "    for bx, p_win in windows:\n",
    "        active = {}\n",
    "        for k, (vx, vy) in p_win.items():\n",
    "            if np.nanstd(vx) >= 0.2 or np.nanstd(vy) >= 0.2:\n",
    "                active[k] = (vx, vy)\n",
    "                \n",
    "        if not active:\n",
    "            continue\n",
    "            \n",
    "        restr_cache = {}\n",
    "        for jB, nB in followers_dict.items():\n",
    "            if jB not in active:\n",
    "                continue\n",
    "            vxB, vyB = active[jB]\n",
    "            YB = zscore(vyB)\n",
    "            XrB = np.c_[make_lags(zscore(vxB), ol, n), make_lags(zscore(vyB), ol, n), make_lags(zscore(bx), ol, n)]\n",
    "            rss_r, nr = ols_rss(YB, XrB)\n",
    "            if not np.isnan(rss_r) and nr >= 20:\n",
    "                restr_cache[jB] = (YB, XrB, rss_r, nr)\n",
    "                \n",
    "        for jB, (YB, XrB, rss_r, nr) in restr_cache.items():\n",
    "            nB = followers_dict[jB]\n",
    "            for jA, nA in leaders_dict.items():\n",
    "                if jA == jB or jA not in active:\n",
    "                    continue\n",
    "                vxA, vyA = active[jA]\n",
    "                Xu = np.c_[XrB, make_lags(zscore(vxA), [lag], n), make_lags(zscore(vyA), [lag], n)]\n",
    "                rss_u, nu = ols_rss(YB, Xu)\n",
    "                if np.isnan(rss_u) or nu < 20 or rss_u < 1e-12:\n",
    "                    continue\n",
    "                dfn = Xu.shape[1] - XrB.shape[1]\n",
    "                dfd = nu - Xu.shape[1] - 1\n",
    "                if dfd < 5 or dfn < 1: \n",
    "                    continue\n",
    "                F = ((rss_r - rss_u) / dfn) / (rss_u / dfd)\n",
    "                if F > f_critical:\n",
    "                    count_df.loc[nA, nB] += 1\n",
    "                    \n",
    "    if outliers:\n",
    "        count_df = count_df.drop(index=outliers, columns=outliers, errors='ignore')\n",
    "        \n",
    "    return count_df\n",
    "\n",
    "print('Self-contained Granger counting engine ready!')\n"
]
nb['cells'][4]['source'] = engine_lines

# Cell 5 (index 5): Recalculating Figure 1 (4 teams)
cell5_source = [
    "print('Recalculating within-team anticipation counts directly from .npz archives...\\n')\n",
    "t0 = time.time()\n",
    "\n",
    "# 1. France (Final vs Argentina)\n",
    "fra_roster = {\n",
    "    'FRA_4':'Varane', 'FRA_5':'Kounde', 'FRA_7':'Griezmann', 'FRA_8':'Tchouameni',\n",
    "    'FRA_9':'Giroud', 'FRA_10':'Mbappe', 'FRA_11':'Dembele', 'FRA_12':'KoloMuani',\n",
    "    'FRA_14':'Rabiot', 'FRA_18':'Upamecano', 'FRA_20':'Coman', 'FRA_22':'THernandez',\n",
    "    'FRA_25':'Camavinga', 'FRA_26':'M.Thuram'\n",
    "}\n",
    "fra_counts = run_window_anticipation_counts(\n",
    "    'data/extracted_features/match_10517_final_features.npz',\n",
    "    fra_roster, fra_roster, outliers=['Kounde']\n",
    ")\n",
    "np.fill_diagonal(fra_counts.values, 0)\n",
    "print(f'Done France in {time.time()-t0:.1f}s')\n",
    "\n",
    "# 2. Argentina (Semi-Final 3-0 vs Croatia)\n",
    "t_team = time.time()\n",
    "arg_roster = {\n",
    "    'ARG_3':'Tagliafico', 'ARG_5':'Paredes', 'ARG_7':'De Paul', 'ARG_9':'Alvarez',\n",
    "    'ARG_10':'Messi', 'ARG_13':'Romero', 'ARG_14':'Palacios', 'ARG_19':'Otamendi',\n",
    "    'ARG_20':'Mac Allister', 'ARG_21':'Dybala', 'ARG_24':'Enzo', 'ARG_25':'L.Martinez', 'ARG_26':'Molina'\n",
    "}\n",
    "arg_counts = run_window_anticipation_counts(\n",
    "    'data/extracted_features/match_10514_argentina_features.npz',\n",
    "    arg_roster, arg_roster, outliers=['Paredes', 'Enzo', 'Palacios']\n",
    ")\n",
    "np.fill_diagonal(arg_counts.values, 0)\n",
    "print(f'Done Argentina in {time.time()-t_team:.1f}s')\n",
    "\n",
    "# 3. Morocco (Semi-Final vs France)\n",
    "t_team = time.time()\n",
    "mar_roster = {\n",
    "    'MAR_2':'Hakimi', 'MAR_3':'Mazraoui', 'MAR_4':'Amrabat', 'MAR_7':'Ziyech',\n",
    "    'MAR_8':'Ounahi', 'MAR_9':'Hamdallah', 'MAR_14':'Aboukhlal', 'MAR_15':'Amallah',\n",
    "    'MAR_17':'Boufal', 'MAR_18':'El Yamiq', 'MAR_19':'En-Nesyri', 'MAR_20':'Dari', 'MAR_25':'Attiyat Allah'\n",
    "}\n",
    "mar_counts = run_window_anticipation_counts(\n",
    "    'data/extracted_features/match_10515_morocco_features.npz',\n",
    "    mar_roster, mar_roster, outliers=['Amrabat']\n",
    ")\n",
    "np.fill_diagonal(mar_counts.values, 0)\n",
    "print(f'Done Morocco in {time.time()-t_team:.1f}s')\n",
    "\n",
    "# 4. Serbia (Group Stage 3-3 vs Cameroon)\n",
    "t_team = time.time()\n",
    "srb_roster = {\n",
    "    'SRB_2':'Pavlovic', 'SRB_4':'Milenkovic', 'SRB_5':'Veljkovic', 'SRB_6':'Maksimovic',\n",
    "    'SRB_7':'Radonjic', 'SRB_9':'A.Mitrovic', 'SRB_10':'Tadic', 'SRB_13':'S.Mitrovic',\n",
    "    'SRB_14':'Zivkovic', 'SRB_16':'Lukic', 'SRB_17':'Kostic', 'SRB_20':'S.Milinkovic',\n",
    "    'SRB_21':'Djuricic', 'SRB_26':'Grujic'\n",
    "}\n",
    "srb_counts = run_window_anticipation_counts(\n",
    "    'data/extracted_features/match_3840_serbia_features.npz',\n",
    "    srb_roster, srb_roster, outliers=[]\n",
    ")\n",
    "np.fill_diagonal(srb_counts.values, 0)\n",
    "print(f'Done Serbia in {time.time()-t_team:.1f}s')\n",
    "\n",
    "print(f'\\nAll 4 teams recalculated from scratch in {time.time()-t0:.1f}s!')\n"
]
nb['cells'][5]['source'] = cell5_source

# Cell 7 (index 7): Cross-team calculation
cross_lines = [
    "print('Recalculating cross-team anticipation networks directly from .npz...')\n",
    "t0 = time.time()\n",
    "\n",
    "arg_cross_roster = {\n",
    "    'ARG_3':'Tagliafico', 'ARG_7':'De Paul', 'ARG_9':'Alvarez', 'ARG_10':'Messi',\n",
    "    'ARG_13':'Romero', 'ARG_19':'Otamendi', 'ARG_20':'Mac Allister', 'ARG_21':'Dybala',\n",
    "    'ARG_26':'Molina'\n",
    "}\n",
    "\n",
    "fra_cross_roster = {\n",
    "    'FRA_4':'Varane', 'FRA_7':'Griezmann', 'FRA_8':'Tchouameni', 'FRA_9':'Giroud',\n",
    "    'FRA_10':'Mbappe', 'FRA_11':'Dembele', 'FRA_12':'KoloMuani', 'FRA_14':'Rabiot',\n",
    "    'FRA_18':'Upamecano', 'FRA_20':'Coman', 'FRA_22':'T.Hernandez', 'FRA_25':'Camavinga', 'FRA_26':'M.Thuram'\n",
    "}\n",
    "\n",
    "# (B) Cross-Team: Argentina Reads France (ARG Leader -> FRA Follower)\n",
    "arg_reads_fra = run_window_anticipation_counts(\n",
    "    'data/extracted_features/match_10517_final_features.npz',\n",
    "    arg_cross_roster, fra_cross_roster\n",
    ")\n",
    "\n",
    "# (C) Cross-Team: France Reads Argentina (FRA Leader -> ARG Follower)\n",
    "fra_reads_arg = run_window_anticipation_counts(\n",
    "    'data/extracted_features/match_10517_final_features.npz',\n",
    "    fra_cross_roster, arg_cross_roster\n",
    ")\n",
    "\n",
    "print(f'Cross-team networks recalculated in {time.time()-t0:.1f}s!')\n"
]
nb['cells'][7]['source'] = cross_lines

# Cell 9 (index 9): Verification of paper statistics
cell9_source = [
    "print('=== VERIFICATION OF PAPER STATISTICS FROM SCRATCH ===')\n",
    "print(f\"France:    Top Pair: Rabiot -> Tchouameni: {fra_counts.loc['Rabiot', 'Tchouameni']} | Reciprocal: Tchouameni -> Rabiot: {fra_counts.loc['Tchouameni', 'Rabiot']}\")\n",
    "print(f\"Argentina: Top Pair: Messi -> Mac Allister: {arg_counts.loc['Messi', 'Mac Allister']} | Alvarez -> Messi: {arg_counts.loc['Alvarez', 'Messi']}\")\n",
    "print(f\"Morocco:   Top Pair: Hakimi -> Ounahi: {mar_counts.loc['Hakimi', 'Ounahi']} | Ziyech <-> Hakimi: {mar_counts.loc['Ziyech', 'Hakimi']} / {mar_counts.loc['Hakimi', 'Ziyech']}\")\n",
    "print(f\"Serbia:    Top Pair: Tadic -> Mitrovic: {srb_counts.loc['Tadic', 'A.Mitrovic']} | Reciprocal: Mitrovic -> Tadic: {srb_counts.loc['A.Mitrovic', 'Tadic']}\")\n",
    "print(f\"Final:     Mac Allister -> Tchouameni: {arg_reads_fra.loc['Mac Allister', 'Tchouameni']}\")\n",
    "print(f\"Final:     Tchouameni -> Mac Allister: {fra_reads_arg.loc['Tchouameni', 'Mac Allister']} | Messi: {fra_reads_arg.loc['Tchouameni', 'Messi']} | Alvarez: {fra_reads_arg.loc['Tchouameni', 'Alvarez']}\")\n"
]
nb['cells'][9]['source'] = cell9_source

with open('notebooks/reproduce_anticipation.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2)

print('Updated notebooks/reproduce_anticipation.ipynb successfully!')
